### ISSUE TITLE
Fix footer

### ISSUE THREAD

**Issue by monsij** [ieeesb-nitdgp/website#22]
The footer contains several invalid information:
![Footer](https://user-images.githubusercontent.com/23289387/72216068-0965c680-3542-11ea-863b-9263f92ed124.JPG)

New details are:

- [ieeesb.nitdgp@gmail.com](mailto:ieeesb.nitdgp@gmail.com)
- 8584970760
- [https://www.facebook.com/nitdgpieeesociety/](https://www.facebook.com/nitdgpieeesociety/)

**Comment by monsij** [comment]
@arkaseth @sayan-mondal-tech  @rimi04  anyone ?

**Comment by sayan-mondal-tech** [comment]
ok i will do it

**Comment by sagar-wal** [comment]
Should I resolve this issue ?

**Comment by sayan-mondal-tech** [comment]
Already solved it and had made a pr

**Comment by sagar-wal** [comment]
Oh, okay.
