### ISSUE TITLE
Add Alumni Section year wise

### ISSUE THREAD

**Issue by ZER-0-NE** [ieeesb-nitdgp/website#27]

**Comment by ZER-0-NE** [comment]
@PaulSoumik where are you placed on this? Do let me know if you need any more clarifications

**Comment by monsij** [comment]
![footer](https://user-images.githubusercontent.com/23289387/77423719-d8352c80-6df5-11ea-8365-68d9d1d3ba71.JPG)

@arkaseth **Resize** and make all the photos uniform. Also **fix** the footer to the bottom of the page.

**Comment by ZER-0-NE** [comment]
@monsij The footer goes away back to the same on refreshing. :p

**Comment by ZER-0-NE** [comment]
And while you're on it @arkaseth  please keep only one "all members" link and not two. Look at the homepage in the Team section
