### ISSUE TITLE
Grunt Editing

### ISSUE THREAD

**Issue by pritish083** [ieeesb-nitdgp/website#31]
1. Team Page 
- Change the year names. Team heads to Core team. Senior Executive, Junior Executive, and Inductees correspondingly.
- Add Chetan's photo
- Delete Amitav' profile
- resize Vaishali's image

2. Edit the " Submit Question " tab under Contact us

3. Re-order the main navigation bar complementing to the vertical order

4. rename "our activities" to "Events"

5. add more photos in the gallery highlighting achievements like FINE, major internships and all.

6. Event page.
- flagship events mei divide karo like Internship BootCamp, SDV and Matlab
- and intellisys and all in a separate section.
- Add SatSiege 
- add carousel of the events conducted

**Comment by PaulSoumik** [comment]
Some changes are not appropriate.

**Comment by pritish083** [comment]
okay!. apart from that let other changes be there
