### ISSUE TITLE
Edit landing page

### ISSUE THREAD

**Issue by pritish083** [ieeesb-nitdgp/website#32]
1. the loading animation is to be changed. Somewhat related to IEEE logo.
2. there should be a carousel in the home page highlighting different genres like
- all events collage
- an attendance of 100+
- an attractive poster for the blog which is linked to blog page
- similarly for research portal
- techX 
- team photo

refer to _**www.ieee.org**_

**Comment by PaulSoumik** [comment]
Some changes are not appropriate.

**Comment by PaulSoumik** [comment]
<
