### ISSUE TITLE
[BUG] Different headers and footers for team and events page

### ISSUE THREAD

**Issue by ZER-0-NE** [ieeesb-nitdgp/website#39]
There's a mismatch of headers and footers for [Team page](http://www.ieeesbnitdgp.com/thereg/members/) and [Events page](http://www.ieeesbnitdgp.com/thereg/).

@arkaseth @sagar-wal @PaulSoumik @pritish083 

PS. Wish I knew WebD :/

**Comment by sagar-wal** [comment]
I am already working on this bug.
