### ISSUE TITLE
Update member info

### ISSUE THREAD

**Issue by monsij** [ieeesb-nitdgp/website#5]
The member page contains several hyperlinks to social media. Update them using the shared drive folder provided earlier in the group.

**Comment by arkaseth** [comment]
I'd like this to be assigned to me

**Comment by monsij** [comment]
There are a few more corrections:
-  Typo in Shubhangee and Shalini Satapathy. 

- Email favicon is not rendering yet 

- Email and LinkedIn icons are swapped for Ishaun.

- Mobile version (m.facebook) is present for Shubhangee. Make it for the desktop version.

- Remove Sudeshna. No longer a valid member.

- Improper Instagram links for Atul, Shalini, Souvik and email for Aman.
