### ISSUE TITLE
Fix Facebook and LinkedIn Buttons

### ISSUE THREAD

**Issue by monsij** [ieeesb-nitdgp/website#6]
The hyperlinks to Facebook (footer) and LinkedIn (sidebar) is not proper.

**Comment by arkaseth** [comment]
I'd like this to be signed to me

**Comment by monsij** [comment]
Already assigned one. Finish it first to start working on this later (if open).

**Comment by arkaseth** [comment]
I've pulled a request for the previous issue.

**Comment by monsij** [comment]
You need to finish it ( get it merged!)
