### ISSUE TITLE
Fix Contact-Us

### ISSUE THREAD

**Issue by monsij** [ieeesb-nitdgp/website#7]
The nav-bar Contact Us button is redirecting to a wrong destination.

**Comment by sagar-wal** [comment]
I'll solve this issue.

**Comment by monsij** [comment]
Also, try making the contact-us form functional. It must redirect all responses towards `ieeesb.nitdgp@gmail.com`

**Comment by sagar-wal** [comment]
> Also, try making the contact-us form functional. It must redirect all responses towards `ieeesb.nitdgp@gmail.com`

Okay
